"""
Polymarket V2 API Credential Generator — Bear Oracle Confirmed Sniper

Reads wallet credentials from 'pre_setup.env', generates API keys via
py-clob-client-v2, and writes the complete config to '.env'.

Usage:
  1. Fill in pre_setup.env:
       POLY_PRIVATE_KEY=0x...
       POLY_FUNDER_ADDRESS=0x...

  2. Run:
       python setup.py

  3. Your .env will be created with all credentials ready for the bot.

Note: The allowance check at the end may show $0.00 — this is a known
cosmetic false alarm in the V2 CLOB backend. Run approve_usdc.py separately
to set on-chain approvals for the V2 exchange contracts.
"""

import sys
from pathlib import Path

from dotenv import dotenv_values, set_key

PRE_SETUP_FILE = "pre_setup.env"
OUTPUT_FILE = ".env"

try:
    from py_clob_client_v2.client import ClobClient
    from py_clob_client_v2.clob_types import ApiCreds, AssetType, BalanceAllowanceParams
    from py_clob_client_v2.constants import POLYGON
except ImportError:
    print("❌ py-clob-client-v2 not installed.")
    print("   Run: pip install -r requirements.txt")
    sys.exit(1)


def run_setup() -> None:
    # ── Read from pre_setup.env ───────────────────────────────────
    if not Path(PRE_SETUP_FILE).exists():
        print(f"❌ '{PRE_SETUP_FILE}' not found.")
        print("   Create it with:")
        print("     POLY_PRIVATE_KEY=0x...")
        print("     POLY_FUNDER_ADDRESS=0x...")
        sys.exit(1)

    pre = dotenv_values(PRE_SETUP_FILE)
    pk = pre.get("POLY_PRIVATE_KEY", "").strip()
    funder = pre.get("POLY_FUNDER_ADDRESS", "").strip()

    if not pk:
        print("❌ POLY_PRIVATE_KEY is missing in pre_setup.env")
        sys.exit(1)

    print("--- Generating API Credentials ---")
    print(f"  Private key: {pk[:6]}...{pk[-4:]}")
    print(f"  Funder: {funder or '(not set)'}")

    # ── Initialize CLOB client (Level 1 — key derivation only) ───
    client = ClobClient(
        host="https://clob.polymarket.com",
        key=pk,
        chain_id=POLYGON,
        funder=funder or None,
    )

    # ── Derive API credentials ────────────────────────────────────
    try:
        creds = client.create_or_derive_api_creds()
    except Exception as exc:
        print(f"❌ Failed to derive API credentials: {exc}")
        sys.exit(1)

    print(f"  API Key:        {creds.api_key}")
    print(f"  API Secret:     {creds.api_secret[:8]}...")
    print(f"  API Passphrase: {creds.api_passphrase[:8]}...")

    # ── Write .env ────────────────────────────────────────────────
    out = Path(OUTPUT_FILE)
    if not out.exists():
        out.write_text("# Generated by setup.py\n")

    set_key(OUTPUT_FILE, "POLY_PRIVATE_KEY", pk)
    set_key(OUTPUT_FILE, "POLY_FUNDER_ADDRESS", funder)
    set_key(OUTPUT_FILE, "POLY_API_KEY", creds.api_key)
    set_key(OUTPUT_FILE, "POLY_API_SECRET", creds.api_secret)
    set_key(OUTPUT_FILE, "POLY_API_PASSPHRASE", creds.api_passphrase)
    set_key(OUTPUT_FILE, "POLY_SIG_TYPE", "0")

    # ── Re-initialize client with Level 2 credentials ────────────
    client = ClobClient(
        host="https://clob.polymarket.com",
        key=pk,
        chain_id=POLYGON,
        funder=funder or None,
        creds=ApiCreds(
            api_key=creds.api_key,
            api_secret=creds.api_secret,
            api_passphrase=creds.api_passphrase,
        ),
    )

    # ── Balance / allowance check (cosmetic — see note above) ─────
    print("\n--- Verifying Balance & Allowance (V2 CLOB view) ---")
    try:
        resp = client.get_balance_allowance(
            params=BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        )
        raw_balance = (
            resp.get("balance", 0)
            if isinstance(resp, dict)
            else getattr(resp, "balance", 0)
        )
        raw_allowance = (
            resp.get("allowance", 0)
            if isinstance(resp, dict)
            else getattr(resp, "allowance", 0)
        )
        balance = float(raw_balance or 0)
        allowance = float(raw_allowance or 0)
        if balance > 1_000_000:
            balance /= 1e6
        if allowance > 1_000_000:
            allowance /= 1e6
        print(f"  Balance:   ${balance:.2f} pUSD")
        print(f"  Allowance: ${allowance:.2f} pUSD")
        if allowance == 0:
            print(
                "  (!) Allowance shows $0.00 — this is a known V2 cosmetic false alarm."
            )
            print("      Run approve_usdc.py to set real on-chain approvals.")
        else:
            print("  Allowance confirmed via CLOB view.")
    except Exception as exc:
        print(f"  Could not verify via CLOB: {exc}")
        print("  Run approve_usdc.py to set on-chain approvals.")

    print(f"\nDone. Credentials written to '{OUTPUT_FILE}'")
    print("Next steps:")
    print("  1. python wrap_pusd.py       — convert USDC.e to pUSD")
    print("  2. python approve_usdc.py    — on-chain approvals for V2 contracts")
    print("  3. python shadow.py          — verify pipeline before trading")


if __name__ == "__main__":
    run_setup()
